In [14]:
import yaml
import pandas as pd

In [36]:
with open("../src/config.yaml", "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

df = pd.read_csv(config["paths"]["raw_data"])

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [37]:
print(df.columns.tolist())

['country', 'iso', 'sex', 'year_of_birth', 'mean_height_(cm)', 'mean_height_lower_95%_uncertainty_interval_(cm)', 'mean_height_upper_95%_uncertainty_interval_(cm)']

In [38]:
print("Linhas após filtro de sexo:", len(df))

Linhas após filtro de sexo: 40400

Filtrar pelo sexo feminino

In [40]:
df_sex = df[df["sex"] == config["filters"]["sex"]]
print("Linhas após filtro de sexo:", len(df_sex))

Linhas após filtro de sexo: 20200

Usar o maior ano disponivel

In [41]:
df_maior_ano = df_sex[df_sex["year_of_birth"] == df_sex["year_of_birth"].max()]
print("Linhas após filtro do ano mais recente:", len(df_maior_ano))

Linhas após filtro do ano mais recente: 200

Media Global

In [42]:
media_global = df_maior_ano["mean_height_(cm)"].mean()
print(f"Altura média global: {media_global:.2f} cm")

Altura média global: 159.49 cm

Altura das mulheres na Russia

In [46]:
altura_m_russia = df_maior_ano[df_maior_ano["country"] == "Russian Federation"]["mean_height_(cm)"].values[0]
print(f"Altura média na Rússia: {altura_m_russia:.2f} cm")

Altura média na Rússia: 165.27 cm

In [47]:
df_maior_ano[df_maior_ano["country"].str.contains("russ", case=False, na=False)]

,country,iso,sex,year_of_birth,mean_height_(cm),mean_height_lower_95%_uncertainty_interval_(cm),mean_height_upper_95%_uncertainty_interval_(cm)
22926,Brunei Darussalam,BRN,Women,1996,153.982486,148.561517,159.332974
35147,Russian Federation,RUS,Women,1996,165.270495,163.972692,166.628603

In [51]:
df_maior_ano.sort_values("mean_height_(cm)", ascending=False).head(30)

,country,iso,sex,year_of_birth,mean_height_(cm),mean_height_lower_95%_uncertainty_interval_(cm),mean_height_upper_95%_uncertainty_interval_(cm)
30097,Latvia,LVA,Women,1996,169.797931,167.043284,172.584208
32925,Netherlands,NLD,Women,1996,168.718579,167.078137,170.345794
26259,Estonia,EST,Women,1996,168.672715,167.835925,169.532037
25148,Czech Republic,CZE,Women,1996,168.457784,166.272592,170.688856
36056,Serbia,SRB,Women,1996,167.690196,166.467410,168.887655
36460,Slovakia,SVK,Women,1996,167.466119,166.105206,168.881163
25249,Denmark,DNK,Women,1996,167.213761,165.637725,168.801157
30602,Lithuania,LTU,Women,1996,166.616088,164.225890,169.064959
21916,Belarus,BLR,Women,1996,166.346561,160.833131,171.920653
39288,Ukraine,UKR,Women,1996,166.339226,160.704158,172.158548
36561,Slovenia,SVN,Women,1996,166.051229,164.781993,167.298963
28380,Iceland,ISL,Women,1996,165.946356,162.658134,169.240818
26562,Finland,FIN,Women,1996,165.897705,164.240103,167.548697
27168,Germany,DEU,Women,1996,165.863595,164.402883,167.340459
21209,Australia,AUS,Women,1996,165.858177,164.721027,167.003486
22623,Bosnia and Herzegovina,BIH,Women,1996,165.848310,163.977727,167.709783
37571,Sweden,SWE,Women,1996,165.697469,163.792520,167.662370
24845,Croatia,HRV,Women,1996,165.631431,163.860453,167.448374
33632,Norway,NOR,Women,1996,165.564902,163.750942,167.396573
38581,Tonga,TON,Women,1996,165.520337,163.801314,167.314249
22017,Belgium,BEL,Women,1996,165.491136,164.140298,166.802435
21815,Barbados,BRB,Women,1996,165.277015,162.709976,167.804663
35147,Russian Federation,RUS,Women,1996,165.270495,163.972692,166.628603
28885,Ireland,IRL,Women,1996,165.113748,163.427460,166.731484
33026,New Zealand,NZL,Women,1996,164.940548,164.070717,165.819472
26663,France,FRA,Women,1996,164.881593,162.877400,166.907712
27370,Greece,GRC,Women,1996,164.874401,163.290169,166.348592
32218,Montenegro,MNE,Women,1996,164.855918,159.479032,170.329642
33430,Niue,NIU,Women,1996,164.796543,162.597633,166.996932
23027,Bulgaria,BGR,Women,1996,164.795359,159.434678,170.007920

In [50]:
ranking = df_maior_ano.sort_values("mean_height_(cm)", ascending=False).reset_index(drop=True)

posicao = ranking[ranking["country"] == "Russian Federation"].index[0] + 1

print("Posição da Rússia no ranking:", posicao)

Posição da Rússia no ranking: 23